version: "3.2"

services:
  dev:
    container_name: dipole-oracle
    image: parity/rust-builder:latest
    working_dir: /var/www/dipole-oracle
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/dipole-oracle/.cargo
    volumes:
      - .:/var/www/dipole-oracle
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/dipole-oracle --dev --ws-external"
